"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { motion } from "framer-motion"
import { Shield, Mail, Lock, Loader2, Building2, Wrench, Building, Zap } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createClient } from "@/lib/supabase/client"
import { toast } from "sonner"
import type { UserRole, CompanyType } from "@/lib/types"

function generateEmail(companyName: string, companyType: CompanyType | null, role: UserRole): string {
  const formatted = companyName.toLowerCase().replace(/\s+/g, ".")
  if (role === "vendor") {
    return `${formatted}@servicesphere.com`
  }
  const domain = companyType === "product" ? "products.servicesphere.com" : "services.servicesphere.com"
  return `${formatted}@${domain}`
}

export default function SignUpPage() {
  const router = useRouter()
  const [isLoading, setIsLoading] = useState(false)
  const [role, setRole] = useState<UserRole>("company")
  const [companyName, setCompanyName] = useState("")
  const [companyType, setCompanyType] = useState<CompanyType | null>(null)
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [useAutoEmail, setUseAutoEmail] = useState(true)
  const [skipEmailVerification, setSkipEmailVerification] = useState(false)

  const handleQuickDemo = (demoRole: UserRole) => {
    setRole(demoRole)
    setCompanyName("Demo Company")
    setCompanyType(demoRole === "company" ? "service" : null)
    setPassword("Demo@123")
    setSkipEmailVerification(true)
    setUseAutoEmail(true)
    toast.success("Demo credentials filled! Click 'Create Account' to continue.")
  }

  const handleSignUp = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)

    try {
      const supabase = createClient()
      const finalEmail = useAutoEmail && companyName ? generateEmail(companyName, companyType, role) : email

      if (!finalEmail) {
        toast.error("Please provide an email or company name")
        setIsLoading(false)
        return
      }

      const { data, error } = await supabase.auth.signUp({
        email: finalEmail,
        password,
        options: {
          emailRedirectTo:
            process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ??
            `${window.location.origin}/auth/callback`,
          data: {
            company_name: companyName,
            role: role,
            company_type: role === "company" ? companyType : null,
          },
        },
      })

      if (error) {
        toast.error(error.message)
        return
      }

      if (data.user) {
        // For demo accounts, auto-login without email verification
        if (skipEmailVerification) {
          const { error: signInError } = await supabase.auth.signInWithPassword({
            email: finalEmail,
            password,
          })
          if (!signInError) {
            toast.success("Demo account created and logged in!")
            if (role === "vendor") {
              router.push("/vendor/dashboard")
            } else {
              router.push("/client/dashboard")
            }
            return
          }
        }
        toast.success("Account created! Please check your email to verify.")
        router.push("/auth/sign-up-success")
      }
    } catch {
      toast.error("An unexpected error occurred")
    } finally {
      setIsLoading(false)
    }
  }

  const autoGeneratedEmail = companyName ? generateEmail(companyName, companyType, role) : ""

  return (
    <div className="min-h-screen flex items-center justify-center bg-background p-4">
      {/* Background decoration */}
      <div className="absolute inset-0 -z-10 overflow-hidden">
        <div className="absolute top-1/4 left-1/4 h-96 w-96 rounded-full bg-primary/5 blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 h-96 w-96 rounded-full bg-secondary/5 blur-3xl" />
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-md"
      >
        <Card className="glass border-border/50">
          <CardHeader className="text-center">
            <Link href="/" className="mx-auto mb-4 flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary">
                <Shield className="h-5 w-5 text-primary-foreground" />
              </div>
              <span className="text-xl font-bold text-foreground">ServiceSphere</span>
            </Link>
            <CardTitle className="text-2xl">Create Account</CardTitle>
            <CardDescription>Join ServiceSphere to manage your SLAs</CardDescription>
          </CardHeader>
          
          <CardContent>
            {/* Quick Demo Section */}
            <div className="mb-6 rounded-lg border-2 border-dashed border-primary/50 bg-primary/5 p-4">
              <div className="flex items-center gap-2 mb-3">
                <Zap className="h-5 w-5 text-primary" />
                <p className="font-semibold text-primary">Quick Demo Login</p>
              </div>
              <p className="text-sm text-muted-foreground mb-3">
                Skip email verification and instantly test the application
              </p>
              <div className="grid grid-cols-2 gap-2">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => handleQuickDemo("company")}
                  className="w-full"
                >
                  <Building2 className="mr-2 h-4 w-4" />
                  Demo Client
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => handleQuickDemo("vendor")}
                  className="w-full"
                >
                  <Wrench className="mr-2 h-4 w-4" />
                  Demo Vendor
                </Button>
              </div>
            </div>

            <Tabs value={role} onValueChange={(v) => setRole(v as UserRole)} className="mb-6">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="company" className="flex items-center gap-2">
                  <Building2 className="h-4 w-4" />
                  Company
                </TabsTrigger>
                <TabsTrigger value="vendor" className="flex items-center gap-2">
                  <Wrench className="h-4 w-4" />
                  Vendor
                </TabsTrigger>
              </TabsList>
            </Tabs>

            <form onSubmit={handleSignUp} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="companyName">Company Name</Label>
                <div className="relative">
                  <Building className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    id="companyName"
                    type="text"
                    placeholder="Your Company Name"
                    value={companyName}
                    onChange={(e) => setCompanyName(e.target.value)}
                    className="pl-10"
                    required
                  />
                </div>
              </div>

              {role === "company" && (
                <div className="space-y-2">
                  <Label htmlFor="companyType">Company Type</Label>
                  <Select 
                    value={companyType || ""} 
                    onValueChange={(v) => setCompanyType(v as CompanyType)}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select company type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="product">Product Company</SelectItem>
                      <SelectItem value="service">Service Company</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              )}

              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label htmlFor="email">Email</Label>
                  <button
                    type="button"
                    onClick={() => setUseAutoEmail(!useAutoEmail)}
                    className="text-xs text-primary hover:underline"
                  >
                    {useAutoEmail ? "Use custom email" : "Use auto-generated"}
                  </button>
                </div>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  {useAutoEmail ? (
                    <Input
                      id="email"
                      type="email"
                      value={autoGeneratedEmail}
                      className="pl-10 bg-muted"
                      readOnly
                    />
                  ) : (
                    <Input
                      id="email"
                      type="email"
                      placeholder="you@example.com"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="pl-10"
                      required
                    />
                  )}
                </div>
                {useAutoEmail && companyName && (
                  <p className="text-xs text-muted-foreground">
                    Auto-generated based on company name
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    id="password"
                    type="password"
                    placeholder="Create a password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="pl-10"
                    required
                    minLength={6}
                  />
                </div>
              </div>

              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating account...
                  </>
                ) : (
                  "Create Account"
                )}
              </Button>
            </form>
          </CardContent>

          <CardFooter className="flex flex-col gap-4">
            <p className="text-center text-sm text-muted-foreground">
              Already have an account?{" "}
              <Link href="/auth/login" className="font-medium text-primary hover:underline">
                Sign in
              </Link>
            </p>
          </CardFooter>
        </Card>
      </motion.div>
    </div>
  )
}
